### ISSUE TITLE
URL for browser extensions has changed

### ISSUE THREAD

**Issue by stvhwrd** [nitoyon/livereloadx#32]
On the LiveReloadX [user documentation page](http://nitoyon.github.io/livereloadx/):

> ### Embed a JavaScript snippet
> You have to embed a JavaScript snippet in HTML pages to enable live reloading.
> 
> Choose one of the following methods to embed the JavaScript snippet.
> 
> * Add manually.
> * Install the [browser extensions](http://feedback.livereload.com/knowledgebase/articles/86242-how-do-i-install-and-use-the-browser-extensions-) (Safari, Chrome and Firefox only).
> * Use static mode
> * Use proxy mode

On the line "Install the browser extensions...", the link should be updated to http://livereload.com/extensions as LiveReload has changed that page's location.

**Comment by nitoyon** [comment]
Thanks!!
